module.exports = {
    ITEM_PER_PAGE: 4,
    TOTAL_PAGING_LINK: 5,
    ITEM_PER_PAGE_PRODUCT: 4,
    ITEM_PER_PAGE_CATEGORY: 4,
    ITEM_PER_PAGE_BRAND: 4,
    ACCOUNT_PER_PAGE: 2,
    ITEM_PER_PAGE_ORDER: 8,
};
